version: "3"
services:
  exerciseandmeditation:
    image: exerciseandmeditation
    ports:
      - "8080:8080"
    networks:
      - exerciseandmeditation-mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/StudentHealth?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:latest
    networks:
      - exerciseandmeditation-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=thisismypassword
      - MYSQL_DATABASE=StudentHealth
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  exerciseandmeditation-mysql: