# Gradle
clean:
	gradle clean

compile:
	gradle build

test:
	gradle test

jar:
	gradle build -x test
	gradle bootJar

run: jar
	echo Starting Spring at:  http://localhost:8080
	java -jar build/libs/StudyHabitsMicroService-1.0.jar

# Docker

docker-build: jar
	docker build -t studyhabits .
	docker images

docker-run: docker-build
	docker run --network studyhabits_network -e "MYSQL_HOST=mysql" --name studyhabits -td -p 80:8080 studyhabits
	docker ps

docker-clean:
	docker stop studyhabits
	docker rm studyhabits
	docker rmi studyhabits

docker-shell:
	docker exec -it studyhabits bash

docker-push:
	docker login
	docker build -t --platform linux/amd64,linux/arm64 lee71559/studyhabits:v1 -t lee71559/studyhabits:v1 .
	docker push lee71559/studyhabits:v1

docker-push-amd64:
	docker buildx ls
	docker buildx create --use
	docker buildx build --platform linux/amd64,linux/arm64 --push -t lee71559/studyhabits:v1 .

docker-mysql:
	docker run --platform linux/x86_64 -d --network studyhabits_network --name mysql -td -p 3306:3306 -e MYSQL_ROOT_PASSWORD=password mysql:8.0

# Compose

network-ls:
	docker network ls

network-create:
	docker network create --driver bridge studyhabits_network

network-prune:
	docker network prune

compose-up:
	docker-compose up --scale studyhabits=1 -d

compose-down:
	docker-compose down